### ISSUE TITLE
post.js always returns blank (empty array)

### ISSUE THREAD

**Issue by michaelpumo** [prismicio/gatsby-blog#1]
I was following this guide and managed to get things running (after some other odd errors):
https://intercom.help/prismicio/en/articles/2933292-sample-blog-with-api-based-cms-gatsby-js

However, when navigating to a blog post after running `gatsby develop`, it simply shows a blank page. In the Prismic repository, all fields are filled in as expected.

Logging `props.data.prismic.allPosts.edges` in `post.js` reveals an empty array. No matter what post is navigated to, it's simply blank.

I feel like there's an issue with the setup/query that fetches the post. It's almost as if the UID is not getting passed correctly?

If I try the query in the GraphiQL playground with the post UID it works but in the template, the exact same query does not return the post.

```
query BlogPostQuery($uid: String!) {
  prismic {
    allPosts(uid: $uid) {
      edges {
        node {
          _meta {
            id
            uid
            type
          }
          title
          date
          body {
            __typename
            ... on PRISMIC_PostBodyText {
              type
              label
              primary {
                text
              }
            }
            ... on PRISMIC_PostBodyQuote {
              type
              label
              primary {
                quote
              }
            }
            ... on PRISMIC_PostBodyImage_with_caption {
              type
              label
              primary {
                image
                caption
              }
            }
          }
        }
      }
    }
  }
}
```

See the screenshot:
<img width="1067" alt="Screenshot 2019-10-13 at 19 20 21" src="https://user-images.githubusercontent.com/4269460/66720003-00ecdb00-edef-11e9-873e-86a18c2866f9.png">

Any ideas what's going on here? On the home page, the post is listed just fine (so of course it does exist).

There are no errors in the web console nor the terminal.

Thanks.

**Comment by hypervillain** [comment]
Hello @michaelpumo, sorry that you encountered such an issue.

Can you try updating `gatsby-source-prismic-graphql` to version `3.4.0-beta.2`?

**Comment by michaelpumo** [comment]
> Hello @michaelpumo, sorry that you encountered such an issue.
> 
> Can you try updating `gatsby-source-prismic-graphql` to version `3.4.0-beta.2`?

Okay, this solved it. Any ideas why, or what was wrong?

Thank you!

**Comment by hypervillain** [comment]
Actually, I'm not sure what is wrong with your version but I noticed some issues were corrected in the beta version. If you're unsure of which version to use, please have a look here:  https://www.npmjs.com/package/gatsby-source-prismic-graphql but I believe always using the beta versions should work just fine.

Let me know if you need more help of course
