### ISSUE TITLE
gatsby build with childImageSharp in query will fail unless gatsby develop is ran first

### ISSUE THREAD

**Issue by MatthewShields** [prismicio/gatsby-blog#5]
When querying for the 'sharp' version of an image field gatsby build will fail unless gatsby develop is ran first. This results in not being able to deploy. 

I have replicated this issue with a fresh pull of this repo and only making this change to the query on the post.js template to ensure that it wasn't any of my other template changes:

```javascript
... on PRISMIC_PostBodyImage_with_caption{
    type
    label
    primary{
        image
        imageSharp {
            absolutePath
            childImageSharp {
                fluid(maxWidth: 800) {
                    ...GatsbyImageSharpFluid
                }
            }
        }
        caption
    }
}
```

Resulting in this error:

![Screenshot of error](https://i.ibb.co/WKmnKKx/Screenshot-2020-04-12-at-20-38-42.png)

When trying to debug the changes I have noticed that there are no cached files created for gatsby-source-prismic-graphql on gatsby build. I removed .cache from .gitignore in order to be able to track the cache files created.

If I remove .cache from .gitignore and I follow the process of:

1. Run Gatsby build - this will fail with the above error and commit cache files
2. Run Gatsby develop - Will notice that a new redux directory has been created

![Screenshot of git changed files](https://i.ibb.co/dpmJBvB/Screenshot-2020-04-12-at-20-47-11.png)

3. Run Gatsby build - this will now succeed and the gatsby-source-prismic-graphql will also now be created and everything works as intended

![Screenshot of git changed files](https://i.ibb.co/VCRQ8Dy/Screenshot-2020-04-12-at-20-51-45.png)

If I was to repeat this process again and remove the created redux files from the cache directory after step 2 before running gatsby build again then the same initial error is given again so I think this is the route of the issue.

After looking in the code as much as I can I can't seem to find what is creating the redux files in the cache directory but I am not an expert at this.

If there is anything I can do to help with this issue please let me know as I am stuck but hit the wall in terms of what my expertise at this will help me debug. Thanks!

(Update - I have created a repo with the example build and the progressive cache commits incase this helps https://github.com/MatthewShields/issue--prismic-blog-gatsby-build)

**Comment by levimykel** [comment]
Hi @MatthewShields, someone will look into this and get back to you with what we find.

**Comment by MatthewShields** [comment]
@levimykel Thanks that would be great :)

**Comment by PaulinaVPG** [comment]
Hello @MatthewShields, the gatsby-source-prismic-graphql plugin has some caching issues. I think this is due to the fact that Prismic already delivers the images pre-processed and optimised through our [Imgix integration](https://user-guides.prismic.io/en/articles/3309829-image-optimization-imgix-integration). So there's really no need to use sharp images.


The Image optimisation article shows you how you can perform the same tasks as sharp image directly in the image url string. [The Imgix documentation](https://docs.imgix.com/) also shows you how you can achieve all the same functionality.

We also recommend: https://github.com/imgix/react-imgix
